name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - htslib=1.17
  - samtools=1.17
  - bcftools=1.17
  - bwa=0.7.17
  - r-dplyr
  - r-ggplot2
  - r-scales
  - r-knitr
  - r-rmarkdown 
  - r-readr
  - r-tidyr
  - r-patchwork